apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: forecast-pipeline-viktor
  annotations:
    scenarios.ai.sap.com/name: "XGB Forecasting"
    scenarios.ai.sap.com/description: "AI Core pipeline for XGBoost batch prediction"
    executables.ai.sap.com/name: "Forecast Executable"
    executables.ai.sap.com/description: "Predict demand for selected material/store"
  labels:
    scenarios.ai.sap.com/id: "xgb"
    ai.sap.com/version: "1.0"
spec:
  entrypoint: run-forecast
  templates:
    - name: run-forecast
      container:
        image: docker.io/viktornazilin1/xgboost-forecasting:latest
        command: ["python"]
        args: ["main_batch.py"]
