apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: forecast-pipeline-viktor-20240418
  annotations:
    scenarios.ai.sap.com/name: "Forecasting Demo"
    scenarios.ai.sap.com/description: "Run XGBoost forecasting in AI Core"
    executables.ai.sap.com/name: "Batch Forecast"
    executables.ai.sap.com/description: "Forecast for all products and stores"
  labels:
    scenarios.ai.sap.com/id: "forecasting"
    ai.sap.com/version: "1.0"
spec:
  entrypoint: run
  templates:
    - name: run
      container:
        image: docker.io/viktornazilin1/xgboost-forecasting:latest
        command: ["python"]
        args: ["main_batch.py"]